### ISSUE TITLE
Environment Issue

### ISSUE THREAD

**Issue by tvy14** [Cinnamon/kotaemon#130]
![image](https://github.com/user-attachments/assets/293820dd-4799-43dd-9d15-f9c0ab826d57)

1. A little issue here, does this has any relation with anything? I'm testing the latest v.0.3.4

2. I saw couple of CMake error during the building, however I didn't see the flow, is there any pre-requisite for the environment before using the latest release?

Any insights and help greatly appreciated. Thank you

**Comment by lone17** [comment]
What commands did you use to install ?
Installing this repo take is a bit different as it is a combination of 2 smaller modules, so you have to install them both manually by following this instruction https://github.com/Cinnamon/kotaemon?tab=readme-ov-file#without-docker

**Comment by tvy14** [comment]
I was following the non-dev version over here: https://cinnamon.github.io/kotaemon/

![image](https://github.com/user-attachments/assets/16781a55-ec09-4c8c-9780-e65d259fcea5)

or you suggest to execute from the developers track? Thank you

**Comment by taprosoft** [comment]
Seem we need to update the non-dev install script @lone17

**Comment by lone17** [comment]
Ah I see. That doc as well as the released package is quite out-of-date unfortunately. The latest feature is currently only in the `main` branch. If you can install from source or use docker, it would be better and you just need to follow the readme. Otherwise you would need to wait for the team to update the doc and test the new release I'm afraid.

@taprosoft yeah, please check my latest request about creating new release. Also I think the team should verify the installation package for end-users. Looks like a lot of people would like to use that.

edit: typos and rephrasing

**Comment by lone17** [comment]
cc @cin-albert @cin-kay I think you can help with this as you have worked on the installation files.

**Comment by taprosoft** [comment]
Will work on the PR and this setup issue soon when I have time.

**Comment by lone17** [comment]
@tvy14 in the mean time, you can try out the app by cloning the live demo and configure it with your openai key.
