### ISSUE TITLE
[BUG] - cant install with docker

### ISSUE THREAD

**Issue by ja49619** [Cinnamon/kotaemon#167]
### Description

Why can't I install using the command from the documentation? What's wrong?

### Reproduction steps

```bash
1. Use this command to launch the server from https://cinnamon.github.io/kotaemon/development/#with-docker-recommended
2. See error

Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
```

### Logs

```bash
docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0

Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
```

### OS

Linux

**Comment by phv2312** [comment]
Hi @ja49619 , Can I have the full logs. With the current log ( from your attached image ) everything seems normal. I can access normally via `localhost:7860`
![image](https://github.com/user-attachments/assets/c7936c77-dd2b-4ee5-acb6-1e0b819c1093)

**Comment by ja49619** [comment]
hi @phv2312 
this was already the full text of the logs

![image](https://github.com/user-attachments/assets/dcba86bb-69a4-41f9-b0b5-65066007d102)

if it's important - docker 27.1.2 ubuntu 24.04 LTS

**Comment by phv2312** [comment]
I found the same issue https://github.com/Cinnamon/kotaemon/issues/132 similar to the one you are facing with. But it occurs mostly on Mac and some Window machine with docker desktop, rarely for Ubuntu
Currently I have no ideas, I and the team will investigate and get back to you soon.

**Comment by phv2312** [comment]
Sorry for bother you but can you please send me the output of the command `grep -m1 -o avx /proc/cpuinfo` ? It does checking the cpu support AVX or not ?

**Comment by ja49619** [comment]
sure
output: avx

update: I rented a completely clean server with Ubuntu 24 and installed your application. Everything worked immediately, so the problem was on my personal server

It turns out this is not a problem with the application, so I’ll figure it out myself

**Comment by R3habDroid** [comment]
CentOS Linux release 7.9.2009 (Core)
Linux version 3.10.0-1160.el7.x86_64 
Same situation:
Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
Watching: '/app' '/app'

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/spaces/lone17/kotaemon (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 15, in <module>
    app = App()
  File "/app/libs/ktem/ktem/app.py", line 42, in __init__
    self._theme = gr.Theme.from_hub("lone17/kotaemon")
  File "/usr/local/lib/python3.10/site-packages/gradio/themes/base.py", line 187, in from_hub
    space_info = api.space_info(name)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2518, in space_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/spaces/lone17/kotaemon (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: a7e2574f-2f91-4de4-947f-b79ec93097d5)')

**Comment by linuaries** [comment]
> CentOS Linux release 7.9.2009 (Core) Linux version 3.10.0-1160.el7.x86_64 Same situation: Warning: Cannot statically find a gradio demo called demo. Reload work may fail. Watching: '/app' '/app'
> 
> [nltk_data] Downloading package punkt_tab to [nltk_data] /usr/local/lib/python3.10/site- [nltk_data] packages/llama_index/core/_static/nltk_cache... [nltk_data] Unzipping tokenizers/punkt_tab.zip. Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) OSError: [Errno 101] Network is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 716, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect self.sock = conn = self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 802, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 594, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/spaces/lone17/kotaemon (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/app/app.py", line 15, in app = App() File "/app/libs/ktem/ktem/app.py", line 42, in **init** self._theme = gr.Theme.from_hub("lone17/kotaemon") File "/usr/local/lib/python3.10/site-packages/gradio/themes/base.py", line 187, in from_hub space_info = api.space_info(name) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2518, in space_info r = get_session().get(path, headers=headers, timeout=timeout, params=params) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send return super().send(request, *args, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/spaces/lone17/kotaemon (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2898ab1c30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: a7e2574f-2f91-4de4-947f-b79ec93097d5)')

I have the same problem, it seems the huggingface.co is blocked. And add HF_ENDPOINT=https://hf-mirror.com also can't solve this issue.

**Comment by Annie0095** [comment]
> ### Description
> Why can't I install using the command from the documentation? What's wrong?
> 
> ### Reproduction steps
> ```shell
> 1. Use this command to launch the server from https://cinnamon.github.io/kotaemon/development/#with-docker-recommended
> 2. See error
> 
> Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
> ```
> 
> ### Logs
> ```shell
> docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0
> 
> Warning: Cannot statically find a gradio demo called demo. Reload work may fail.
> Watching: '/app' '/app'
> 
> [nltk_data] Downloading package punkt_tab to
> [nltk_data]     /usr/local/lib/python3.10/site-
> [nltk_data]     packages/llama_index/core/_static/nltk_cache...
> [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
> ```
> 
> ### OS
> Linux

The same problem，so sad,and i want to run this docker offline

**Comment by ivanovd** [comment]
You are downloading from a fork repository from what I can see:

`docker run -e GRADIO_SERVER_NAME=0.0.0.0 -e GRADIO_SERVER_PORT=7860 -p 7860:7860 -it --rm taprosoft/kotaemon:v1.0`

Notice: **taprosoft/kotaemon:v1.0**

If you want to use this repo your command should be: 

`docker run \
-e GRADIO_SERVER_NAME=0.0.0.0 \
-e GRADIO_SERVER_PORT=7860 \
-p 7860:7860 -it --rm \
ghcr.io/cinnamon/kotaemon:latest`

eg: **ghcr.io/cinnamon/kotaemon:latest**

I also used that repo before and I got the same error as you. If I use this one - everything works fine.

**Comment by ja49619** [comment]
> I also used that repo before and I got the same error as you. If I use this one - everything works fine.

nice 👍👍,
I didn't check the docker image tags, I just took the text from the developer documentation
