### ISSUE TITLE
[BUG] - <Embedding dimension mismatch error during file upload with local LLM and Ollama embeddings>

### ISSUE THREAD

**Issue by Lee-Ju-Yeong** [Cinnamon/kotaemon#348]
### Description

I encountered an error while uploading a file using the local LLM and setting embeddings with Ollama. Even though the embedding dimensions were set to 1536 in the Resources tab under Embedding settings, the embeddings generated were still 768, which caused a dimension mismatch error. Below is the error trace.

### Reproduction steps

```bash
1.Set up a local LLM.
2.Configure embeddings with Ollama.
3.In the Resources tab, set dimensions to 1536 in the Embedding settings.
4.Upload a file for indexing.
5.Observe the error regarding embedding dimension mismatch.
```

### Screenshots

<img width="883" alt="image" src="https://github.com/user-attachments/assets/8444eb3e-0142-457a-b3ab-1891ab2042b2">
<img width="869" alt="image" src="https://github.com/user-attachments/assets/cf2606c6-b875-444e-9959-e4221291ed9f">

### Logs

```bash
User-id: 1, can see public conversations: True
Fast indexing mode: False
Reader mode: default
Reader in use: <kotaemon.loaders.html_loader.HtmlReader object at 0x307eec940>
Got 0 page thumbnails
Adding documents to doc store
Getting embeddings for 20 nodes
Adding embeddings to vector store
Embedding dimension 768 does not match collection dimensionality 1536
Traceback (most recent call last):
  File "/Users/zooyong/Documents/Kotaemon/libs/ktem/ktem/index/file/pipelines.py", line 851, in stream
    file_id, docs = yield from pipeline.stream(
  ...
  File "/opt/miniconda3/envs/kotaemon/lib/python3.10/site-packages/chromadb/api/segment.py", line 880, in _validate_dimension
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Embedding dimension 768 does not match collection dimensionality 1536
```

**Comment by Lee-Ju-Yeong** [comment]
i deleted user_data folder and tried again. then it works.

**Comment by jppaolim** [comment]
Same problem here and can't manage to solve the way it is decribed. Furthermore, to me the problem is the dimensionality of chroma DB creation not the dimensionality of ollama embeddings .... Does the fix actually create the chroma DB the right way ?  @taprosoft

**Comment by christopherkao** [comment]
I got into this same problem when I swapped out the embedding model to another one in ollama which has a different dimensionality (3584) from the chroma DB dimensionality (768):

```
ERROR:ktem.index.file.pipelines:Embedding dimension 3584 does not match collection dimensionality 768
```

The dimensionality of the default `nomic-embed-text` is 768: https://huggingface.co/nomic-ai/nomic-embed-text-v1.5. 

I found code in chroma.py that could delete a collection, so that a new collection could be initiated with the 3584 dimensionality based on the first embedding received:
```
    def drop(self):
        """Delete entire collection from vector stores"""
        self._client.client._client.delete_collection(self._client.client.name)
``` 

I ended up figuring out a way via Python3 shell to remove a collection, based on the chroma.py file libs/kotaemon/kotaemon/storages/vectorstores/chroma.py:
```
import chromadb
client = chromadb.PersistentClient(path="./chroma")
client.delete_collection(name="default")

# confirmed it did not exist anymore
client.get_collection(name="default")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/chromadb/api/client.py", line 172, in get_collection
    model = self._server.get_collection(
  File "/usr/local/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/chromadb/api/segment.py", line 103, in wrapper
    return self._rate_limit_enforcer.rate_limit(func)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/chromadb/rate_limit/simple_rate_limit/__init__.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/chromadb/api/segment.py", line 289, in get_collection
    raise InvalidCollectionException(f"Collection {name} does not exist.")
chromadb.errors.InvalidCollectionException: Collection default does not exist.
```

I then stopped the docker container and restarted it, hoping that a new chroma db collection would get created. It turned out that no chroma db collection was created, but logs from docker made it seem like something had been created. 

I haven't figured it out fully yet, but wanted to leave some learnings here.
